django-upload-download/file_download/urls.py
from django.urls import re_path

from . import views

# namespace
app_name = "file_download"

urlpatterns = [
    re_path(
        r"^download/(?P<file_path>.*)/$",
        views.file_response_download,
        name="file_download",
    ),
]

django-upload-download/file_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("file/", include("file_upload.urls")),
    path("file/", include("file_download.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-upload-download/file_upload/urls.py
from django.urls import re_path, path
from . import views

# namespace
app_name = "file_upload"

urlpatterns = [
    # Upload File
    re_path(r"^upload/$", views.file_upload, name="file_upload"),
    # View File List
    path("", views.file_list, name="file_list"),
]

django-upload-download/file_download/models.py
from django.db import models

# Create your models here.

django-upload-download/file_upload/models.py
from django.db import models
import os
import uuid


def user_directory_path(filename: str):
    ext = filename.split(".")[-1]
    filename = "{}.{}".format(uuid.uuid4().hex[:10], ext)
    return os.path.join("files", filename)


class File(models.Model):
    file = models.FileField(upload_to='uploads/')
    # Important to add index
    file_name = models.CharField(max_length=255, db_index=True, default='')
    file_size = models.IntegerField(db_index=True, default=0)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

django-upload-download/file_upload/forms.py
from django import forms


ALLOWED_EXTENSIONS = ["jpg", "jpeg", "png", "gif", "pdf", "doc", "docx", "xls", "xlsx", "log", "txt"]


# Regular form
class FileUploadForm(forms.Form):
    file = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"class": "form-control"})
    )

    def clean_file(self):
        file = self.cleaned_data["file"]
        ext = file.name.split(".")[-1].lower()
        # Check file extension, limiting file extenstions for security
        if ext not in ALLOWED_EXTENSIONS:
            raise forms.ValidationError(f"{ext} files are not allowed.")
        # return cleaned data is very important.
        return file

django-upload-download/file_download/views.py
import os

from django.http import Http404, FileResponse


# Limit file download type
def file_response_download(request, file_path: str) -> FileResponse:
    ext = os.path.basename(file_path).split(".")[-1].lower()
    # cannot be used to download py, db and sqlite3 files.
    if ext not in ["py", "db", "sqlite3"]:
        response = FileResponse(open(file_path, "rb"))
        response["content_type"] = "application/octet-stream"
        response["Content-Disposition"] = "attachment; filename=" + os.path.basename(
            file_path
        )
        return response
    else:
        raise Http404

django-upload-download/file_upload/views.py
import os
import uuid

from django.shortcuts import render, redirect

from .forms import FileUploadForm
from .models import File


# Show file list
def file_list(request):
    files = File.objects.all().order_by("-id")
    return render(request, "file_upload/file_list.html", {"files": files})


# Regular file upload without using ModelForm
def file_upload(request):
    if request.method == "POST":
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            # get cleaned data
            raw_file = form.cleaned_data.get("file")
            # Limit file size to 10MB
            if raw_file.size < 1024 * 1024 * 10:
                new_file = File()
                new_file.file = handle_uploaded_file(raw_file)
                new_file.file_name = raw_file.name
                new_file.file_size = raw_file.size
                new_file.save()
                return redirect("/file/")
    else:
        form = FileUploadForm()

    return render(
        request,
        "file_upload/upload_form.html",
        {"form": form, "heading": "Upload files with Regular Form"},
    )


def handle_uploaded_file(file):
    ext = file.name.split(".")[-1]
    file_name = "{}.{}".format(uuid.uuid4().hex[:10], ext)
    # file path relative to 'media' folder
    file_path = os.path.join("files", file_name)
    absolute_file_path = os.path.join("media", "files", file_name)

    directory = os.path.dirname(absolute_file_path)
    if not os.path.exists(directory):
        os.makedirs(directory)

    with open(absolute_file_path, "wb+") as destination:
        for chunk in file.chunks():
            destination.write(chunk)

    return file_path

django-upload-download/file_upload/templates/file_upload/base.html
{% load static %}

<html lang="en">
<head>
<title>{% block title %}Django File Upload and Download{% endblock %} </title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>

<body>
 <!-- Page content of course! -->
<main class="container-fluid">
<div class="container">

 {% block content %} {% endblock %}

</div> 
</main>


<!-- Bootstrap core JavaScript
================================================== -->

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% block js %} {% endblock %}

</body>
</html>

django-upload-download/file_upload/templates/file_upload/file_list.html
{% extends "file_upload/base.html" %}

{% block content %}
<h3>File List</h3>
<h2> <a href="/file/upload/">Upload File</a></h2>
{% if files %}
<table class="table table-striped">

    <tbody>
    <tr>
        <td>Filename & URL</td>
        <td>File size</td>
        <td>Uploaded at</td>
    </tr>
    {% for file in files %}
    <tr>
        <td><a href="/file/download{{ file.file.url }}/">{{ file.file.url }}</a></td>
        <td>{{ file.file_size }}</td>
        <td>{{ file.upload_method }}</td>
        <td>{{ file.timestamp }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% else %}
<p>No files uploaded yet. Please click <a href="{% url 'file_upload:file_upload' %}">here</a>
    to upload files.</p>
{% endif %}

{% endblock %}

django-upload-download/file_upload/templates/file_upload/upload_form.html
{% extends "file_upload/base.html" %}
{% block content %}
{% if heading %}
<h3>{{ heading }}</h3>
{% endif %}

<form action="" method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {{ form.as_p }}
 <button class="btn btn-info form-control " type="submit" value="submit">Upload</button>
</form>

{% endblock %}